#!/bin/bash
echo Checking for updates - Apt, Yum, Flatpak

if hash apt 2>/dev/null; then
  sudo apt update
  sudo apt list --upgradable
  sudo apt -f install
  sudo apt upgrade -yy
  sudo apt autoremove -yy
  sudo apt clean -yy
fi

if hash yum 2>/dev/null; then
  sudo yum update -yy  
fi

if hash flatpak 2>/dev/null; then
  sudo flatpak update -yy
fi

if hash pihole 2>/dev/null; then
  pihole -up
fi

# if hash pip 2>/dev/null; then
#   sudo python3 -m pip install -U pip
#   pip3 install pip-review
#   sudo python3 -m pip_review --local --auto
# fi

echo Update complete
