#!/bin/bash

##
# Linux Updater tool. Runs through a number of possible linuxy updating solutions and 
# if they are available, run each updater.
# 
# Types Available:
# - Apt
# - Nala (Apt frontend)
# - Snap
# - Flatpak
# - Yum
# - PiHole
# - Pip3 - Only lists updates.
#
# Would like to add:
# - DNF
# - Pacman
#
# Todo:
# - Add flags to skip individual packages - for example, `--skip-pip`.
# - Add flag to force Apt over Nala.
#
# Author:
# Gareth Palmer [@projector22]
##

echo Checking for updates - Apt, Yum, Flatpak

echo -e "\nUpdating this script."
cd ~/bin
git pull

if hash nala 2>/dev/null; then
  # Repo: https://gitlab.com/volian/nala
  echo -e "\nNALA"
  sudo nala upgrade -yy
  sudo nala install --fix-broken
  sudo nala autoremove -yy
  sudo nala clean
elif hash apt 2>/dev/null; then
  echo -e "\nAPT"
  sudo apt update
  sudo apt list --upgradable
  sudo apt --fix-broken install
  sudo apt full-upgrade -yy
  sudo apt autoremove -yy
  sudo apt clean -yy
  echo -e "Apt update complete"
fi

if hash snap 2>/dev/null; then
  echo -e "\nSNAP"
  sudo snap refresh
  echo -e "snap update complete"
fi

if hash yum 2>/dev/null; then
  echo -e "\nYUM"
  sudo yum update -yy
  echo -e "yum update complete"
fi

if hash flatpak 2>/dev/null; then
  echo -e "\nFLATPAK"
  sudo flatpak update -yy
  echo -e "flatpak update complete"
fi

if hash pihole 2>/dev/null; then
  echo -e "\nPIHOLE"
  pihole -up
  echo -e "pihole update complete"
fi

if hash pip3 2>/dev/null; then
  echo -e "\nPIP3 - run pip3 install -U APPNAME to update an individual package\n"
  pip3 list --outdated
  # pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U 
fi

echo -e "\n\nAll updates complete"
